---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cert-monitor-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cert-monitor-controller
  template:
    metadata:
      labels:
        name: cert-monitor-controller
    spec:
      serviceAccountName: "certmonctrl-{{ .Release.Name }}"
      containers:
        - name: cert-monitor-controller
          image: '{{ .Values.certMonitorController.image }}'
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: metrics

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: cert-monitor-controller
spec:
  ports:
    - name: metrics
      port: 3000
      protocol: TCP
  selector:
    name: cert-monitor-controller

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cert-monitor-controller
spec:
  selector:
    matchLabels:
      name: cert-monitor-controller
  endpoints:
    - port: metrics

...
