{{ if ne (toString .Values.imagePullSecret.registry) "" }}
---

apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  labels:
    app.kubernetes.io/name: cert-monitor-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
  name: cert-monitor-controller-registry
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.imagePullSecret.registry (printf "%s:%s" .Values.imagePullSecret.user .Values.imagePullSecret.password | b64enc) | b64enc }}

...
{{ end }}
