---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-monitor-controller
  labels:
    app.kubernetes.io/name: cert-monitor-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-monitor-controller
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cert-monitor-controller
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
      name: cert-monitor-controller
    spec:
      containers:
        - name: cert-monitor-controller
          image: '{{ .Values.image }}'
          imagePullPolicy: '{{ .Values.imagePullPolicy }}'
          ports:
            - containerPort: 3000
              name: metrics
          args:
            - '-log-level'
            - '{{ .Values.logLevel }}'
            - '-metrics-prefix'
            - '{{ .Values.metricsPrefix }}'
{{ if ne (toString .Values.imagePullSecret.registry) "" }}
      imagePullSecrets:
        - name: cert-monitor-controller-registry
{{ end }}
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
      serviceAccountName: "certmonctrl-{{ .Release.Name }}"

...
