{{ if .Values.monitoring.enabled }}
---

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/name: cert-monitor-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
  name: cert-monitor-controller
spec:
  groups:
    - name: "cert-monitor-controller.rules"
      rules:
        - alert: CertificateExpiresSoon
          for: 1m
          expr: {{ .Values.metricsPrefix }}_expires_in < {{ .Values.monitoring.alertWhenExpiresLessThan }}
          annotations:
            message: 'The certificate in {{ "{{ $labels.exported_namespace }}/{{ $labels.name }}" }} at key {{ "{{ $labels.key }}" }} {{ "{{ if gt $value 0.0 }}" }}will expire in less than {{ .Values.monitoring.alertWhenExpiresLessThan }}h:{{ "{{ else }}" }}has expired:{{ "{{ end }}" }} {{ "{{ printf \"%.1f\" $value }}" }}h'

...
{{ end }}
